CREATE TABLE feed_impression (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id UUID      NOT NULL,
    spot_id   BIGINT    NOT NULL,
    shown_at  TIMESTAMP NOT NULL,
    CONSTRAINT fk_feed_impression_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_feed_impression_spot FOREIGN KEY (spot_id) REFERENCES spot (id),
    CONSTRAINT uk_feed_impression_member_spot UNIQUE (member_id, spot_id)
);

CREATE INDEX idx_feed_impression_member_shown_at ON feed_impression (member_id, shown_at);
