-- 공지사항 (MY-04). 어드민이 등록·수정하고 앱은 visible 상태만 최신순으로 읽는다.
CREATE TABLE notice (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         VARCHAR(20)  NOT NULL,
    title        VARCHAR(100) NOT NULL,
    content      TEXT         NOT NULL,
    visible      BOOLEAN      NOT NULL DEFAULT TRUE,
    published_at DATE         NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL
);

-- 앱 목록: WHERE visible = TRUE ORDER BY published_at DESC, id DESC (커서 페이징)
CREATE INDEX idx_notice_visible_published ON notice (visible, published_at DESC, id DESC);
