-- FAQ (MY-05). 유형(카테고리)별로 묶이고 유형 순서·항목 순서는 어드민이 정한다.
CREATE TABLE faq_category (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50) NOT NULL,
    sort_order INT         NOT NULL,
    visible    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP   NOT NULL,
    updated_at TIMESTAMP   NOT NULL
);

CREATE TABLE faq (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT       NOT NULL REFERENCES faq_category (id),
    question    VARCHAR(200) NOT NULL,
    answer      TEXT         NOT NULL,
    sort_order  INT          NOT NULL,
    visible     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_faq_category_sort ON faq (category_id, sort_order);
