-- 약관 (MY-07). 종류별로 버전을 쌓고, 앱은 시행일이 지난 최신 버전 하나만 읽는다.
-- 시행된 버전은 회원이 동의한 문서라 수정하지 않는다 (애플리케이션에서 막음).
CREATE TABLE policy (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         VARCHAR(30) NOT NULL,
    version      VARCHAR(20) NOT NULL,
    content      TEXT        NOT NULL,
    effective_at DATE        NOT NULL,
    created_at   TIMESTAMP   NOT NULL,
    updated_at   TIMESTAMP   NOT NULL,
    CONSTRAINT uk_policy_type_version UNIQUE (type, version)
);

-- 앱 조회: WHERE type = ? AND effective_at <= today ORDER BY effective_at DESC, id DESC LIMIT 1
CREATE INDEX idx_policy_type_effective ON policy (type, effective_at DESC, id DESC);
