-- 관리자 변경 요청 감사 로그. /api/admin/** 의 POST/PUT/PATCH/DELETE 가 2xx 로 끝나면 한 줄 남긴다.
-- 요청 본문은 저장하지 않는다(개인정보). 상세는 request_id 로 앱 로그와 대조한다.
CREATE TABLE admin_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id    UUID         NOT NULL,
    method      VARCHAR(10)  NOT NULL,
    path        VARCHAR(300) NOT NULL,
    status_code INT          NOT NULL,
    request_id  VARCHAR(64),
    created_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_admin_audit_log_admin_id ON admin_audit_log (admin_id, id DESC);
