-- 앱 API(/api/**, 관리자 제외) 요청 기록. 관리자가 회원별 호출 이력을 볼 때 쓴다.
-- 요청 본문·헤더는 저장하지 않는다(개인정보). 상세는 request_id 로 앱 로그와 대조한다.
-- 트래픽이 관리자 API보다 훨씬 많으므로 admin.api-log.retention-days(기본 30일) 지나면 배치로 지운다.
CREATE TABLE api_request_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   UUID,                    -- 비회원·인증 실패 요청은 NULL
    method      VARCHAR(10)  NOT NULL,
    path        VARCHAR(300) NOT NULL,
    status_code INT          NOT NULL,
    duration_ms INT          NOT NULL,
    request_id  VARCHAR(64),
    created_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_api_request_log_member_id ON api_request_log (member_id, id DESC);
CREATE INDEX idx_api_request_log_created_at ON api_request_log (created_at);
