-- 운영 콘텐츠는 회원 생성 루트와 수명을 분리한다. 컨텍스트 간 FK는 두지 않는다.
CREATE TABLE recommended_route (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    image_url VARCHAR(2000) NOT NULL,
    region VARCHAR(100) NOT NULL,
    visible BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL CHECK (sort_order >= 0),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
CREATE TABLE recommended_route_stop (
    recommended_route_id BIGINT NOT NULL REFERENCES recommended_route(id) ON DELETE CASCADE,
    spot_id BIGINT NOT NULL,
    day_number INTEGER NOT NULL CHECK (day_number BETWEEN 1 AND 5),
    sequence INTEGER NOT NULL CHECK (sequence BETWEEN 1 AND 6),
    PRIMARY KEY (recommended_route_id, day_number, sequence),
    UNIQUE (recommended_route_id, spot_id)
);
CREATE INDEX idx_recommended_route_order ON recommended_route (sort_order, id);
CREATE TABLE recommended_area (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level VARCHAR(30) NOT NULL,
    region VARCHAR(100) NOT NULL,
    district VARCHAR(100),
    neighborhood VARCHAR(100),
    label VARCHAR(200) NOT NULL,
    sort_order INTEGER NOT NULL CHECK (sort_order >= 0),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_recommended_area_order ON recommended_area (sort_order, id);
CREATE TABLE survey_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mood VARCHAR(30) NOT NULL,
    spot_id BIGINT NOT NULL,
    image_url VARCHAR(2000) NOT NULL,
    sort_order INTEGER NOT NULL CHECK (sort_order >= 0),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_survey_image_order ON survey_image (sort_order, id);

-- 기존 앱의 영문 약관 계약을 유지한다. 기존 동의의 버전은 추정해 채우지 않는다.
ALTER TABLE policy ADD COLUMN locale VARCHAR(10) NOT NULL DEFAULT 'en-US';
ALTER TABLE policy ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE policy ADD COLUMN visible BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE policy DROP CONSTRAINT uk_policy_type_version;
ALTER TABLE policy ADD CONSTRAINT uk_policy_type_version_locale UNIQUE (type, version, locale);
CREATE INDEX idx_policy_publication ON policy (type, locale, enabled, visible, effective_at DESC, id DESC);
ALTER TABLE member_agreement ADD COLUMN policy_id BIGINT;
ALTER TABLE member_agreement ADD COLUMN policy_version VARCHAR(20);
ALTER TABLE member_agreement ADD COLUMN policy_locale VARCHAR(10);
