CREATE TABLE spot (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id     VARCHAR(50)  NOT NULL,
    content_type   VARCHAR(30)  NOT NULL,
    area           VARCHAR(50)  NOT NULL,
    source         VARCHAR(30)  NOT NULL,
    longitude      DOUBLE PRECISION,
    latitude       DOUBLE PRECISION,
    tel            VARCHAR(100),
    route_excluded BOOLEAN      NOT NULL DEFAULT FALSE,
    status         VARCHAR(30)  NOT NULL,
    lcls_systm1    VARCHAR(20),
    lcls_systm2    VARCHAR(20),
    lcls_systm3    VARCHAR(20),
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL,
    CONSTRAINT uk_spot_source_content_id UNIQUE (source, content_id)
);

CREATE TABLE spot_translation (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spot_id    BIGINT       NOT NULL,
    locale     VARCHAR(10)  NOT NULL,
    title      VARCHAR(500) NOT NULL,
    overview   TEXT,
    addr1      VARCHAR(500),
    addr2      VARCHAR(500),
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT fk_spot_translation_spot FOREIGN KEY (spot_id) REFERENCES spot (id),
    CONSTRAINT uk_spot_translation_spot_locale UNIQUE (spot_id, locale)
);

CREATE INDEX idx_spot_translation_spot_id ON spot_translation (spot_id);

CREATE TABLE spot_image (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spot_id    BIGINT        NOT NULL,
    image_url  VARCHAR(1000) NOT NULL,
    is_primary BOOLEAN       NOT NULL DEFAULT FALSE,
    sort_order INT           NOT NULL DEFAULT 0,
    created_at TIMESTAMP     NOT NULL,
    updated_at TIMESTAMP     NOT NULL,
    CONSTRAINT fk_spot_image_spot FOREIGN KEY (spot_id) REFERENCES spot (id)
);

CREATE INDEX idx_spot_image_spot_id ON spot_image (spot_id);
