CREATE TABLE spot_mood (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spot_id     BIGINT           NOT NULL,
    mood_vector JSONB            NOT NULL,
    mood_tags   JSONB            NOT NULL,
    confidence  DOUBLE PRECISION,
    created_at  TIMESTAMP        NOT NULL,
    updated_at  TIMESTAMP        NOT NULL,
    CONSTRAINT fk_spot_mood_spot FOREIGN KEY (spot_id) REFERENCES spot (id),
    CONSTRAINT uk_spot_mood_spot_id UNIQUE (spot_id)
);

CREATE INDEX idx_spot_mood_tags ON spot_mood USING GIN (mood_tags jsonb_path_ops);
