CREATE TABLE bookmark (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  UUID         NOT NULL,
    spot_id    BIGINT       NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT fk_bookmark_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_bookmark_spot FOREIGN KEY (spot_id) REFERENCES spot (id),
    CONSTRAINT uk_bookmark_member_spot UNIQUE (member_id, spot_id)
);

CREATE INDEX idx_bookmark_member_created_at ON bookmark (member_id, created_at DESC, id DESC);
CREATE INDEX idx_bookmark_spot_id ON bookmark (spot_id);
