CREATE TABLE spot_description (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spot_id    BIGINT       NOT NULL REFERENCES spot (id),
    locale     VARCHAR(10)  NOT NULL DEFAULT 'ko-KR',
    content    TEXT         NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at TIMESTAMP    NOT NULL DEFAULT now(),
    UNIQUE (spot_id, locale)
);
