CREATE TABLE route (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id  UUID         NOT NULL,
    member_id  UUID         NOT NULL,
    title      VARCHAR(40)  NOT NULL,
    start_date DATE         NOT NULL,
    end_date   DATE         NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT fk_route_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT uk_route_public_id UNIQUE (public_id)
);

CREATE INDEX idx_route_member_id ON route (member_id);

CREATE TABLE route_day (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id   BIGINT  NOT NULL,
    day_number INT     NOT NULL,
    date       DATE    NOT NULL,
    CONSTRAINT fk_route_day_route FOREIGN KEY (route_id) REFERENCES route (id),
    CONSTRAINT uk_route_day_route_day_number UNIQUE (route_id, day_number)
);

CREATE TABLE route_spot (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_day_id      BIGINT           NOT NULL,
    spot_id           BIGINT           NOT NULL,
    sequence          INT              NOT NULL,
    estimated_minutes INT              NOT NULL,
    spot_title        VARCHAR(500)     NOT NULL,
    spot_image_url    VARCHAR(1000),
    spot_area         VARCHAR(50)      NOT NULL,
    spot_district     VARCHAR(30),
    spot_latitude     DOUBLE PRECISION,
    spot_longitude    DOUBLE PRECISION,
    spot_content_type VARCHAR(30)      NOT NULL,
    CONSTRAINT fk_route_spot_route_day FOREIGN KEY (route_day_id) REFERENCES route_day (id),
    CONSTRAINT uk_route_spot_day_sequence UNIQUE (route_day_id, sequence)
);

CREATE INDEX idx_route_spot_spot_id ON route_spot (spot_id);

CREATE TABLE route_leg (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_day_id     BIGINT      NOT NULL,
    from_sequence    INT         NOT NULL,
    to_sequence      INT         NOT NULL,
    travel_mode      VARCHAR(20) NOT NULL,
    duration_seconds INT         NOT NULL,
    distance_meters  INT         NOT NULL,
    landing_url      VARCHAR(1000),
    CONSTRAINT fk_route_leg_route_day FOREIGN KEY (route_day_id) REFERENCES route_day (id)
);
